export enum SupportedNetworksId {
  // mainnets
  ETHEREUM_MAINNET = 'ETHEREUM_MAINNET',
  BASE_MAINNET = 'BASE_MAINNET',
  ARBITRUM_ONE_MAINNET = 'ARBITRUM_ONE_MAINNET',
  BNB_MAINNET = 'BNB_MAINNET',
  POLYGON_POS_MAINNET = 'POLYGON_POS_MAINNET',

  // testnets
  ETHEREUM_HOLESKY = 'ETHEREUM_HOLESKY',
  ETHEREUM_SEPOLIA = 'ETHEREUM_SEPOLIA',
}
