/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Docs
 * API description
 * OpenAPI spec version: 1.0
 */

export type WalletControllerGetValidatorSchemaV1200 = { [key: string]: unknown };
