export enum SupportedNetworksId {
  ETHEREUM_MAINNET = 'ETHEREUM_MAINNET',
  BASE_MAINNET = 'BASE_MAINNET',
  ARBITRUM_MAINNET = 'ARBITRUM_MAINNET',
  ETHEREUM_HOLESKY = 'ETHEREUM_HOLESKY',
  ETHEREUM_SEPOLIA = 'ETHEREUM_SEPOLIA',
}
