/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Docs
 * API description
 * OpenAPI spec version: 1.0
 */
import type { NetworkId } from './networkId';

export interface DepositDetailsDto {
  address: string;
  currencyId: string;
  networkId: NetworkId;
}
