/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Docs
 * API description
 * OpenAPI spec version: 1.0
 */
import type { NetworkResponseDtoId } from './networkResponseDtoId';
import type { NetworkResponseDtoNetworkType } from './networkResponseDtoNetworkType';

export interface NetworkResponseDto {
  id: NetworkResponseDtoId;
  name: string;
  displayName: string;
  networkType: NetworkResponseDtoNetworkType;
  isTestnet: boolean;
}
