/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Docs
 * API description
 * OpenAPI spec version: 1.0
 */

export type NetworkResponseDtoNetworkType = typeof NetworkResponseDtoNetworkType[keyof typeof NetworkResponseDtoNetworkType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NetworkResponseDtoNetworkType = {
  EVM: 'EVM',
  SOLANA: 'SOLANA',
} as const;
