/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Docs
 * API description
 * OpenAPI spec version: 1.0
 */

export type NetworkId = typeof NetworkId[keyof typeof NetworkId];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NetworkId = {
  ETHEREUM_MAINNET: 'ETHEREUM_MAINNET',
  BASE_MAINNET: 'BASE_MAINNET',
  ARBITRUM_MAINNET: 'ARBITRUM_MAINNET',
  ETHEREUM_HOLESKY: 'ETHEREUM_HOLESKY',
} as const;
