/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Docs
 * API description
 * OpenAPI spec version: 1.0
 */

export type TokenResponseDtoStandard = typeof TokenResponseDtoStandard[keyof typeof TokenResponseDtoStandard];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TokenResponseDtoStandard = {
  NATIVE: 'NATIVE',
  ERC20: 'ERC20',
  BEP20: 'BEP20',
  TRC20: 'TRC20',
  SPL: 'SPL',
} as const;
