/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Docs
 * API description
 * OpenAPI spec version: 1.0
 */
import type { TokenResponseDtoStandard } from './tokenResponseDtoStandard';
import type { TokenResponseDtoNetworkId } from './tokenResponseDtoNetworkId';

export interface TokenResponseDto {
  id: string;
  canonicalTokenId: string;
  standard: TokenResponseDtoStandard;
  address: string;
  /** @minimum 0 */
  decimals: number;
  symbol: string;
  isDeprecated: boolean;
  networkId: TokenResponseDtoNetworkId;
}
