/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * API Docs
 * API description
 * OpenAPI spec version: 1.0
 */
import type { WebhookActivityDtoNetwork } from './webhookActivityDtoNetwork';

export interface WebhookActivityDto {
  webhookId: string;
  createdAt: string;
  fromAddress: string;
  toAddress: string;
  network: WebhookActivityDtoNetwork;
  address: string;
  hash: string;
}
